site_name: Huggingface Docs

theme:
  name: 'material'

nav:
    - 欢迎来到Hugging Face: 'index.md'
    - 第一章：引言:
        - 1.1 HuggingFace的历史: '1、引言\1.1 HuggingFace的历史.md'
        - 1.2 本书的目标和读者: '1、引言\1.2 本书的目标和读者.md'
        - 1.3 对深度学习的介绍: '1、引言\1.3 对深度学习的介绍.md'
    - 第二章：初识HuggingFace:
        - 2.1 环境配置: '2、初识HuggingFace\2.1 环境配置.md'
        - 2.2 你的第一个HuggingFace程序: '2、初识HuggingFace\2.2 你的第一个HuggingFace程序.md'
        - 2.3 通过AutoClass来实现: '2、初识HuggingFace\2.3 通过AutoClass来实现.md'
        - 2.4 从头训练一个模型: '2、初识HuggingFace\2.4 从头训练一个模型.md'
    - 第三章：数据预处理:
        - 3.1 tokenizer: '3、数据预处理\3.1 tokenizer.md'
        - 3.2 Padding 和 Truncation: '3、数据预处理\3.2 Padding 和 Truncation.md'
        - 3.3 图片的预处理: '3、数据预处理\3.3 图片的预处理.md'
    - 第四章：加载数据:
        - 4.1 理解Datasets: '4、加载数据\4.1 理解Datasets.md'
        - 4.2 从Hub加载数据: '4、加载数据\4.2 从Hub加载数据.md'
        - 4.3 从本地加载数据: '4、加载数据\4.3 从本地加载数据.md'
        - 4.4 映射式和迭代式: '4、加载数据\4.4 映射式和迭代式.md'
        - 4.5 数据集shuffle: '4、加载数据\4.5 数据集shuffle.md'
    - 第五章：定义模型结构:
         - 5.1 从Hub加载模型: '5、定义模型结构\5.1 从Hub加载模型.md'
         - 5.2 修改预训练模型: '5、定义模型结构\5.2 修改预训练模型.md'
         - 5.3 通过配置加载模型: '5、定义模型结构\5.3 通过配置加载模型.md'
         - 5.4 自定义一个模型: '5、定义模型结构\5.4 自定义一个模型.md'
    - 第六章：训练一个模型:
         - 6.1 利用Trainer进行训练: '6、训练一个模型\6.1 利用Trainer进行训练.md'
         - 6.2 训练中的一些重要参数: '6、训练一个模型\6.2 训练中的一些重要参数.md'
         - 6.3 自定义训练: '6、训练一个模型\6.3 自定义训练.md'
         - 6.4 模型的保存和加载: '6、训练一个模型\6.4 模型的保存和加载.md'
    - 第七章：训练进阶:
         - 7.1 混合精度训练: '7、训练进阶\7.1 混合精度训练.md'
         - 7.2 分布式训练-数据并行: '7、训练进阶\7.2 分布式训练-数据并行.md'
         - 7.3 分布式训练-模型并行: '7、训练进阶\7.3 分布式训练-模型并行.md'
         - 7.4 其他: '7、训练进阶\7.4 其他.md'
    - 第八章：模型评估: '8、模型评估\8 模型评估.md'
    - 第九章：模型推理: '9、模型推理\9 模型推理.md'
    - 第十章：NLP常见任务:
         - 10.1 文本分类: '10、NLP常见任务\10.1 文本分类.md'
         - 10.2 命名实体识别: '10、NLP常见任务\10.2 命名实体识别.md'
         - 10.3 文本生成: '10、NLP常见任务\10.3 文本生成.md'
    - 第十一章：利用Llma2创建你的聊天机器人: '11、利用Llma2创建你的聊天机器人\11 利用Llma2创建你的聊天机器人.md'
    - 第十二章：计算机视觉常见任务:
         - 12.1 图像预处理: '12、计算机视觉常见任务\12.1 图像预处理.md'
         - 12.2 图像分类: '12、计算机视觉常见任务\12.2 图像分类.md'
         - 12.3 目标检测: '12、计算机视觉常见任务\12.3 目标检测.md'
         - 12.4 语义分割: '12、计算机视觉常见任务\12.4 语义分割.md'
    - 第十三章：语音识别任务: '13、语音识别任务\13 语音识别任务.md'
    - 第十四章：多模态任务:
         - 14.1 多模态预处理: '14、多模态任务\14.1 多模态预处理.md'
         - 14.2 多模态任务示例: '14、多模态任务\14.2 多模态任务示例.md'